2023-05-20 22:12:20,956 ERROR [DBInstaller] org.h2.jdbc.JdbcSQLNonTransientException: Type de données inconnu: "IDG"
Unknown data type: "IDG"; SQL statement:
CREATE TABLE groupe ("
                    + "idg INT PRIMARY KEY,"
                    + "nomg VARCHAR(50)"
                    + ");
CREATE TABLE etudiant ("
                    + "id INT PRIMARY KEY AUTO_INCREMENT,"
                    + "nom VARCHAR(50),"
                    + "prenom VARCHAR(50),"
                    + "telephone1 VARCHAR(15),"
                    + "telephone2 VARCHAR(15),"
                    + "adresse VARCHAR(100),"
                    + "email_personnel VARCHAR(100),"
                    + "email_professionnel VARCHAR(100),"
                    + "genre VARCHAR(10),"
                    + "idg INT,"
                    + "FOREIGN KEY (idg) REFERENCES groupe(idg)"
                    + ");
 [50004-214]
2023-05-21 15:34:00,858 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CONTACT" non trouvée
Table "CONTACT" not found; SQL statement:
SELECT * from contact where upper(nom)=? and upper(prenom)=? [42102-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8398)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
	at org.h2.command.Parser.readTableOrView(Parser.java:8358)
	at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
	at org.h2.command.Parser.readTableReference(Parser.java:2334)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
	at org.h2.command.Parser.parseSelect(Parser.java:2878)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at data.ContactDao.rechercherContactParNom(ContactDao.java:21)
	at bll.ContaManager.ajouterContact(ContaManager.java:18)
	at ihm.Main.main(Main.java:95)
2023-05-21 17:04:35,061  INFO [Main] La base de données est crée correctement
2023-05-21 17:20:28,101 ERROR [DBConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: La base de données est peut-être en cours d'utilisation: "C:/Users/hp/note.mv.db". Solutions posibles: fermer toutes les autres connexions; utilisez le mode serveur
Database may be already in use: "C:/Users/hp/note.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-21 17:23:47,508 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CONTACT" non trouvée
Table "CONTACT" not found; SQL statement:
SELECT * FROM contact WHERE telephone1 = ? OR telephone2 = ? [42102-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8398)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
	at org.h2.command.Parser.readTableOrView(Parser.java:8358)
	at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
	at org.h2.command.Parser.readTableReference(Parser.java:2334)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
	at org.h2.command.Parser.parseSelect(Parser.java:2878)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:199)
	at ihm.Main.main(Main.java:111)
2023-05-28 19:31:31,547 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "NUMERO_PROFESSIONNEL" non trouvée
Column "NUMERO_PROFESSIONNEL" not found; SQL statement:
DELETE FROM etudiant WHERE numero_professionnel = ? OR numero_personnel = ? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:139)
	at org.h2.expression.condition.ConditionAndOr.optimize(ConditionAndOr.java:136)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Delete.doPrepare(Delete.java:112)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at data.ContactDao.delete(ContactDao.java:169)
	at ihm.Main.main(Main.java:176)
2023-05-28 19:33:48,388 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:93)
	at ihm.Main.main(Main.java:152)
2023-05-28 19:34:19,559 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:93)
	at ihm.Main.main(Main.java:152)
2023-05-28 19:35:54,921 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.rechercherContactParNom1(ContactDao.java:264)
	at ihm.Main.main(Main.java:133)
2023-05-28 21:08:51,253 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.updateContact(ContactDao.java:143)
	at ihm.Main.main(Main.java:231)
2023-05-28 21:10:59,319 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.updateContact(ContactDao.java:143)
	at ihm.Main.main(Main.java:231)
2023-05-28 21:20:57,129 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.updateContact(ContactDao.java:143)
	at ihm.Main.main(Main.java:231)
2023-05-28 21:25:06,813 ERROR [DBConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: La base de données est peut-être en cours d'utilisation: "C:/Users/hp/note.mv.db". Solutions posibles: fermer toutes les autres connexions; utilisez le mode serveur
Database may be already in use: "C:/Users/hp/note.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-28 21:26:00,256 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.updateContact(ContactDao.java:143)
	at ihm.Main.main(Main.java:231)
2023-05-28 21:31:47,467 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.updateContact(ContactDao.java:143)
	at ihm.Main.main(Main.java:231)
2023-05-28 21:44:04,272 ERROR [ContactDao] Erreur due à : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.updateContact(ContactDao.java:145)
	at ihm.Main.main(Main.java:231)
2023-05-28 22:33:26,044 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:187)
	at ihm.Main.main(Main.java:191)
2023-05-28 22:43:32,966 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1041)
	at data.ContactDao.create(ContactDao.java:44)
	at bll.ContaManager.ajouterContact(ContaManager.java:24)
	at ihm.Main.main(Main.java:97)
2023-05-28 22:48:07,766 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1041)
	at data.ContactDao.create(ContactDao.java:44)
	at bll.ContaManager.ajouterContact(ContaManager.java:24)
	at ihm.Main.main(Main.java:97)
2023-05-28 22:59:32,436 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:220)
	at ihm.Main.main(Main.java:113)
2023-05-28 23:00:06,181 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:220)
	at ihm.Main.main(Main.java:113)
2023-05-28 23:08:59,795 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:93)
	at ihm.Main.main(Main.java:153)
2023-05-28 23:09:58,454 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:220)
	at ihm.Main.main(Main.java:112)
2023-05-28 23:10:27,036 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:220)
	at ihm.Main.main(Main.java:112)
2023-05-28 23:34:11,840 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:220)
	at ihm.Main.main(Main.java:112)
2023-05-28 23:39:12,786 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:92)
	at ihm.Main.main(Main.java:153)
2023-05-28 23:42:28,331 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:92)
	at ihm.Main.main(Main.java:153)
2023-05-28 23:44:48,315 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:97)
	at ihm.Main.main(Main.java:153)
2023-05-28 23:48:18,796 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLNonTransientException: L'objet est déjà fermé
The object is already closed [90007-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:206)
	at data.ContactDao.getAllContacts(ContactDao.java:93)
	at ihm.Main.main(Main.java:153)
2023-05-28 23:52:24,354 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "SELECT * FROM etudiant WHERE telephone1 = ? OR telephone2 = [*]"; attendu "ALL (, ANY (, SOME ("
Syntax error in SQL statement "SELECT * FROM etudiant WHERE telephone1 = ? OR telephone2 = [*]"; expected "ALL (, ANY (, SOME ("; SQL statement:
SELECT * FROM etudiant WHERE telephone1 = ? OR telephone2 =  [42001-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.getSyntaxError(DbException.java:261)
	at org.h2.command.Parser.getSyntaxError(Parser.java:900)
	at org.h2.command.Parser.readTermWithoutIdentifier(Parser.java:5197)
	at org.h2.command.Parser.readTerm(Parser.java:4901)
	at org.h2.command.Parser.readFactor(Parser.java:3398)
	at org.h2.command.Parser.readSum(Parser.java:3385)
	at org.h2.command.Parser.readConcat(Parser.java:3350)
	at org.h2.command.Parser.readComparison(Parser.java:3328)
	at org.h2.command.Parser.readConditionRightHandSide(Parser.java:3195)
	at org.h2.command.Parser.readCondition(Parser.java:3144)
	at org.h2.command.Parser.readExpressionPart2(Parser.java:3060)
	at org.h2.command.Parser.readExpressionWithGlobalConditions(Parser.java:3049)
	at org.h2.command.Parser.parseSelect(Parser.java:2881)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:666)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at data.ContactDao.findContactByPhoneNumber(ContactDao.java:213)
	at ihm.Main.main(Main.java:112)
2023-05-29 00:54:17,121 ERROR [DBConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: La base de données est peut-être en cours d'utilisation: "C:/Users/hp/note.mv.db". Solutions posibles: fermer toutes les autres connexions; utilisez le mode serveur
Database may be already in use: "C:/Users/hp/note.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-31 23:10:23,893 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ETUDIANT" not found (this database is empty); SQL statement:
SELECT * FROM etudiant [42104-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8385)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
	at org.h2.command.Parser.readTableOrView(Parser.java:8358)
	at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
	at org.h2.command.Parser.readTableReference(Parser.java:2334)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
	at org.h2.command.Parser.parseSelect(Parser.java:2878)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:92)
	at data.ContactDao.getAllContacts(ContactDao.java:94)
	at ihm.Main.main(Main.java:153)
2023-05-31 23:12:13,366  INFO [Main] La base de données est crée correctement
2023-06-01 12:20:51,941  INFO [Main] La base de données est crée correctement
2023-06-04 01:15:29,058 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Intégrité référentielle violation de contrainte: "CONSTRAINT_6F: PUBLIC.ETUDIANT_GROUPE FOREIGN KEY(ID_ETUDIANT) REFERENCES PUBLIC.ETUDIANT(ID) (5)"
Referential integrity constraint violation: "CONSTRAINT_6F: PUBLIC.ETUDIANT_GROUPE FOREIGN KEY(ID_ETUDIANT) REFERENCES PUBLIC.ETUDIANT(ID) (5)"; SQL statement:
DELETE FROM etudiant WHERE telephone1 = ? OR telephone2 = ? [23503-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:365)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:382)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:256)
	at org.h2.table.Table.fireConstraints(Table.java:1172)
	at org.h2.table.Table.fireAfterRow(Table.java:1190)
	at org.h2.command.dml.Delete.update(Delete.java:92)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at data.ContactDao.delete(ContactDao.java:181)
	at ihm.Main.main(Main.java:316)
2023-06-08 02:35:48,345  INFO [Main] La base de données est crée correctement
2023-06-08 02:55:35,742 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "id_etudiant" non trouvée
Column "id_etudiant" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at data.ContactDao.updateContact(ContactDao.java:169)
	at ihm.Main.main(Main.java:371)
2023-06-08 03:04:32,268 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "id_etudiant" non trouvée
Column "id_etudiant" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at data.ContactDao.updateContact(ContactDao.java:174)
	at ihm.Main.main(Main.java:371)
2023-06-08 03:18:11,767 ERROR [DBConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: La base de données est peut-être en cours d'utilisation: "C:/Users/hp/sami.mv.db". Solutions posibles: fermer toutes les autres connexions; utilisez le mode serveur
Database may be already in use: "C:/Users/hp/sami.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-06-08 03:19:09,224 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "id_etudiant" non trouvée
Column "id_etudiant" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at data.ContactDao.updateContact(ContactDao.java:174)
	at ihm.Main.main(Main.java:371)
2023-06-08 03:43:03,454 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLDataException: Valeur trop longue pour la colonne "TELEPHONE2 CHARACTER VARYING(15)": "'444444444444444444' (18)"
Value too long for column "TELEPHONE2 CHARACTER VARYING(15)": "'444444444444444444' (18)"; SQL statement:
INSERT INTO etudiant(nom, prenom, telephone1, telephone2, adresse, email_personnel, email_professionnel, genre) VALUES (?, ?, ?, ?, ?, ?, ?, ?) [22001-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getValueTooLongException(DbException.java:322)
	at org.h2.value.Value.getValueTooLongException(Value.java:2573)
	at org.h2.value.Value.convertToVarchar(Value.java:1261)
	at org.h2.value.Value.convertTo(Value.java:1117)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:926)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)
	at org.h2.command.CommandContainer.update(CommandContainer.java:163)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at data.ContactDao.create(ContactDao.java:59)
	at bll.ContaManager.ajouterContact(ContaManager.java:28)
	at ihm.Main.main(Main.java:106)
2023-06-08 03:47:20,859 ERROR [ContactDao] Erreur à cause de : 
org.h2.jdbc.JdbcSQLSyntaxErrorException: La fonction "DOUBLE_METAPHONE" n'a pas été trouvée
Function "DOUBLE_METAPHONE" not found; SQL statement:
SELECT * FROM etudiant WHERE double_metaphone(nom) = ? [90022-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.readFunction(Parser.java:3847)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5211)
	at org.h2.command.Parser.readTerm(Parser.java:4901)
	at org.h2.command.Parser.readFactor(Parser.java:3398)
	at org.h2.command.Parser.readSum(Parser.java:3385)
	at org.h2.command.Parser.readConcat(Parser.java:3350)
	at org.h2.command.Parser.readCondition(Parser.java:3132)
	at org.h2.command.Parser.readExpressionWithGlobalConditions(Parser.java:3043)
	at org.h2.command.Parser.parseSelect(Parser.java:2881)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at data.ContactDao.rechercherContactParNomPhonetique(ContactDao.java:401)
	at ihm.Main.main(Main.java:201)
